name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

#    - name: configure
#      run: ./configure

    - name: Install Go Toolchain
      run: sudo apt install -y golang-go && echo "installed golang"

    - name: Install govunlcheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

#    - name: Install govunlcheck
#      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      
#    - name: Install dependencies
#      run: make

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
