name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#env:
  #GOROOT: "/opt/local/go"
  #GOPATH: "/home/runner/go"
  #PATH: "/opt/local/go/bin:/usr/bin:/usr/sbin:/home/runner/go/bin"
  #GOVERSION: "go1.24.1.linux-amd64.tar.gz"
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.24.1
           go-package: ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...