name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#env:
  #GOROOT: "/opt/local/go"
  #GOPATH: "/home/runner/go"
  #PATH: "/opt/local/go/bin:/usr/bin:/usr/sbin:/home/runner/go/bin"
  #GOVERSION: "go1.24.1.linux-amd64.tar.gz"
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.24.1
           go-package: ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    - name: Build
      run: go build -v ./...
    - name: Capture ENV 
      run: env | grep -i -e go
    - name: Test
      run: go test -v ./...